name: Spring Boot CI with JDK 21

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up environment variables for MySQL
      env:
        MYSQL_HOST: 47.99.66.142
        MYSQL_PORT: 3306
        MYSQL_USER: TODOJAVA
        MYSQL_PASSWORD: 123456
        MYSQL_DATABASE: todo
      run: echo "MYSQL environment variables are set"

    - name: Build and Test
      working-directory: backend/
      run: mvn -B package --file pom.xml

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: backend/target/surefire-reports/*.xml
